mysql:
  credentials:
    user: root
    password: pass1234
    db: kingdoms
    host: 127.0.0.1
  save-interval: 10 mins
  tables:
    - players
    - kingdoms
permissions:
  home:
    - admin
    - mod
    - trusted
    - member
    - guest
  build:
    - admin
    - mod
    - trusted
  interact:
    - admin
    - mod
    - trusted
  invite:
    - admin
    - mod
    - trusted
  kick:
    - admin
    - mod
  sethome:
  rename:
  assign:
    - admin
  claim:
    - admin